verbose: false
logType: '{{ getEnv("LOG_TYPE", "flat") }}'
server:
  debug: false
  routes:
    state:
      failAction: 'ignore'
  port: "{{ getEnv('PORT', 8080) }}"
  address: '0.0.0.0'
routePrefix: "{{ getEnv('ROUTE_PREFIX', getEnv('PATH_PREFIX', '')) }}"
plugins:
  hapi-config-route:
    _enabled: '{{ envExists("CONFIG_KEY") }}'
    key: '{{ENV.CONFIG_KEY}}'
  hapi-health:
    token: "{{ getEnv('HEALTH_TOKEN', false) }}"
    endpoint: "{{routePrefix}}/health"
  hapi-logr:
    reporters:
      flat:
        reporter: 'logr-flat'
        options:
          timestamp: false
          appColor: true
          enabled: '{{logType === "flat"}}'
          theme:
            keys: 'cyan'
          tagColors:
            redirect: 'bgBlue'
            not-found: 'bgBlue'
            user-error: 'bgYellow'
            server-error: 'bgRed'
      consoleColor:
        reporter: 'logr-console-color'
        options:
          enabled: '{{logType === "cli"}}'
          timestamp: false
          appColor: true
      bell:
        reporter: 'logr-reporter-bell'
        options:
          enabled: '{{logType === "cli"}}'
  hapi-timing:
    _enabled: "{{ truthy(ENV.TIMING) }}"
    threshold: '{{ parseInt(getEnv("SLOW_THRESHOLD", "300")) }}'
  hapi-cache-stats:
    interval: '{{ getEnv("CACHE_STATS", false) }}'
    _enabled: '{{ envExists("CACHE_STATS") }}'
    verbose: '{{ truthy(ENV.CACHE_STATS_VERBOSE) }}'
  hapi-oppsy:
    _enabled: '{{ getEnv("OPS_INTERVAL", false) }}'
    interval: '{{ parseInt(getEnv("OPS_INTERVAL", "0")) }}'
    logCpu: false
    logMemory: false
  "@firstandthird/hapi-require-https":
    _enabled: '{{ truthy(ENV.FORCE_HTTPS) }}'
  hapi-method-loader:
    cwd: '{{CWD}}'
    verbose: '{{verbose}}'
  hapi-route-loader:
    _dependencies:
      - 'hapi-method-loader'
    cwd: '{{CWD}}'
    prefix: '{{routePrefix}}'
    verbose: '{{verbose}}'
  hapi-log-response:
    requests: '{{ truthy(ENV.ACCESS_LOGS) }}'
    _dependencies:
      - 'hapi-trailing-slash'
    tags:
      - 'detailed-response'
  hapi-trailing-slash:
    method: 'remove'
