verbose: false
logType: '{{ENV.LOG_TYPE || "flat" }}'
server:
  debug: false
  routes:
    state:
      failAction: 'ignore'
  port: "{{ENV.PORT || 8080}}"
  address: '0.0.0.0'
routePrefix: "{{ ENV.PATH_PREFIX || '' }}"
plugins:
  "@firstandthird/hapi-require-https":
    _enabled: '{{ENV.FORCE_HTTPS === "true"}}'
    _dependencies:
      - 'hapi-logr'
  hapi-trailing-slash:
    method: 'remove'
    _dependencies:
      - 'hapi-route-loader'
  hapi-method-loader:
    _dependencies:
      - '@firstandthird/hapi-require-https'
    cwd: '{{CWD}}'
    verbose: '{{verbose}}'
  hapi-route-loader:
    _dependencies:
      - 'hapi-method-loader'
    cwd: '{{CWD}}'
    prefix: '{{routePrefix}}'
    verbose: '{{verbose}}'
  hapi-logr:
    clientErrorsToWarnings: true
    requests: '{{ENV.ACCESS_LOGS === "true" || ENV.ACCESS_LOGS === true }}'
    reporters:
      flat:
        reporter: 'logr-flat'
        options:
          timestamp: false
          appColor: true
          enabled: '{{logType === "flat"}}'
          theme:
            keys: 'cyan'
      consoleColor:
        reporter: 'logr-console-color'
        options:
          enabled: '{{logType === "cli"}}'
          timestamp: false
          appColor: true
      bell:
        reporter: 'logr-reporter-bell'
        options:
          enabled: '{{logType === "cli"}}'
  hapi-log-response:
    _dependencies:
      - 'hapi-trailing-slash'
    tags:
      - 'detailed-response'
