server:
  debug:
    request:
      - 'error'
connection:
  port: 80
  address: '0.0.0.0'
  routes:
    response:
      failAction: 'log'
    validate:
      options:
        allowUnknown: true
mongo:
  host: 'localhost'
  port: '27017'
  db: 'rapptor-app'
structure:
  routes: 'routes'
  assets: 'public'
  views: 'public'
  helpers: 'helpers'
  methods: 'methods'
  partials: 'partials'
routes:
  base: '/'
  context: {}
assets:
  path: '/ui'
  compiled: '_prod'
  mapping: '_prod/assets.json'
views:
  errors: false
cache:
  partition: 'raptor-catbox'
