verbose: false
server:
  debug: false
connection:
  port: "{{ENV.PORT || 8080}}"
  address: '0.0.0.0'
plugins:
  hapi-logr:
    _priority: 1
    type: 'json'
    renderOptions:
      console:
        pretty: true
  hapi-method-loader:
    _priority: 2
    cwd: '{{CWD}}'
    verbose: '{{verbose}}'
  hapi-route-loader:
    _priority: 3
    cwd: '{{CWD}}'
    verbose: '{{verbose}}'
