name: 'rapptor'
verbose: false
logType: '{{ envVars.logType }}'
server:
  debug: false
  routes:
    state:
      failAction: 'ignore'
  port: "{{ envVars.port }}"
  address: '0.0.0.0'
routePrefix: "{{ envVars.routePrefix }}"
sentryFilter:
  - 'error'
  - 'warning'
  - 'user-error'
  - 'server-error'
  - 'sentry'

plugins:
  hapi-health:
    token: "{{ envVars.healthToken }}"
    endpoint: "{{routePrefix}}/health"
    auth: false
  hapi-logr:
    unhandledRejection: true
    uncaughtException: true
    reporters:
      logfmt:
        reporter: 'logr-logfmt'
        options:
          enabled: '{{logType === "logfmt"}}'
      consoleColor:
        reporter: 'logr-console-color'
        options:
          enabled: '{{logType === "cli"}}'
          timestamp: false
          appColor: true
      bell:
        reporter: 'logr-reporter-bell'
        options:
          enabled: '{{logType === "cli"}}'
      sentry:
        reporter: 'logr-sentry'
        options:
          enabled: '{{(envVars.sentryDsn) ? true : false}}'
          dsn: '{{envVars.sentryDsn}}'
          environment: '{{env}}'
          logger: '{{name}}'
          filter: '{{sentryFilter}}'
  hapi-timing:
    _enabled: "{{ envVars.timing }}"
    threshold: '{{ envVars.threshold }}'
  hapi-cache-stats:
    interval: '{{ envVars.cacheStatsInterval }}'
    _enabled: '{{ envVars.cacheStatsEnabled }}'
    verbose: '{{ envVars.cacheStatsVerbose }}'
  hapi-oppsy:
    _enabled: '{{ envVars.opsEnabled }}'
    interval: '{{ envVars.opsInterval }}'
    logCpu: false
    logMemory: false
  hapi-require-https:
    _enabled: '{{ envVars.forceHttps }}'
  hapi-method-loader:
    cwd: '{{CWD}}'
    verbose: '{{verbose}}'
  hapi-route-loader:
    _dependencies:
      - 'hapi-method-loader'
    cwd: '{{CWD}}'
    prefix: '{{routePrefix}}'
    verbose: '{{verbose}}'
  hapi-log-response:
    requests: '{{ envVars.logRequests }}'
    includeEventTags: true
    ignoreUnauthorizedTry: true
    _dependencies:
      - 'hapi-trailing-slash'
    tags:
      - 'detailed-response'
  hapi-trailing-slash:
    method: 'remove'
