connection:
  port: 80
  address: '0.0.0.0'
mongo:
  host: 'localhost'
  port: '27017'
  db: 'rapptor-app'
structure:
  routes: 'routes'
  assets: 'public'
  views: 'public'
  helpers: 'helpers'
  methods: 'methods'
logging:
  opsInterval: 15000
  reporters:
    console: false
    mongodb:
      enabled: true
      args:
        - 'MONGOURL'
        -
           ttl: 604800
           events:
            response: '*'
            log: '*'
            error: '*'
    hipchat:
      enabled: false
      args:
        - 
          auth_token: ''
          room: ''
          roomToken: ''
          debug: true
          notify: false
          events:
            log:
              response-errors:
                color: 'yellow'
                notify: false
            error:
              '*':
                color: 'red'
                notify: true
assets:
  path: '/ui'
views:
  layouts:
    - 'common/layout'
cache:
  partition: 'raptor-catbox'
plugins:
  good-mongodb-viewer:
    _nativePlugin: true
    connectionUrl: 'MONGOURL'
    endpoint: '/_logs'
    searches:
      #'Response Errors': 'event:log AND tags:response-errors'
      Jobs: 'tags:agenda'
  hapi-log-response:
    _nativePlugin: true
    enabled: false
    excludeStatus: [200, 206, 304, 302, 404]
    tags: ['response-errors']
  hapi-redirects:
    _nativePlugin: true
    redirects: {}
  hapi-agenda:
    _nativePlugin: true
    mongoUrl: 'MONGOURL'
    jobs: 'DIRNAME/jobs'
    processEvery: '30 minutes'
    every: {}
  hapi-metrics:
    connectionUrl: 'MONGOURL'
    collection: 'rapptor-metrics'
