connection:
  port: 80
  address: '0.0.0.0'
mongo:
  host: 'localhost'
  port: '27017'
  db: 'rapptor-app'
structure:
  routes: 'routes'
  assets: 'public'
  views: 'public'
  helpers: 'helpers'
logging:
  opsInterval: 15000
  reporters:
    console: false
    mongodb:
      enabled: true
      args:
        - 'MONGOURL'
        -
           ttl: 604800
           events:
            request: '*'
            log: '*'
            error: '*'
    hipchat:
      enabled: false
      args:
        - 
          auth_token: ''
          room: ''
          roomToken: ''
          debug: true
          notify: false
          events:
            log:
              request-errors:
                color: 'yellow'
                notify: false
            error:
              '*':
                color: 'red'
                notify: true
assets:
  path: '/ui'
views:
  layouts:
    - 'common/layout'
cache:
  partition: 'raptor-catbox'
plugins:
  good-mongodb-viewer:
    connectionUrl: 'MONGOURL'
    endpoint: '/_logs'
    searches:
      Responses: 'event:log AND tags:request-errors'
      Jobs: 'tags:agenda'
  hapi-log-response:
    enabled: false
    excludeStatus: [200, 206, 304, 302, 404]
    tags: ['request-errors']
  hapi-redirects:
    redirects: {}
  hapi-agenda:
    mongoUrl: 'MONGOURL'
    jobs: 'DIRNAME/jobs'
    processEvery: '30 minutes'
    every: {}
