verbose: false
connection:
  port: "{{ENV.PORT || 8080}}"
  address: '0.0.0.0'
logging:
  reporters:
    json-console:
      events:
        error:
        log:
plugins:
  hapi-method-loader:
    cwd: '{{CWD}}'
    verbose: '{{verbose}}'
  hapi-route-loader:
    cwd: '{{CWD}}'
    verbose: '{{verbose}}'
