name: 'rapptor'
host: ''
server:
  debug:
    request:
      - 'error'
connection:
  port: "{{default ENV.PORT 8080}}"
  address: '0.0.0.0'
  routes:
    response:
      failAction: 'log'
    validate:
      options:
        allowUnknown: true
mongo:
  url: "mongodb://{{default ENV.MONGO_PORT_27017_TCP_ADDR 'localhost'}}:{{default ENV.MONGO_PORT_27017_TCP_PORT 27017}}/{{name}}-app"
structure:
  routes: 'routes'
  assets: 'public'
  views: 'public'
  helpers: 'helpers'
  methods: 'methods'
  partials: 'public'
routes:
  base: '/'
  context: {}
assets:
  host: '{{host}}' #CDN goes here
  path: '/ui'
  compiled: '_prod'
  mapping: '_prod/assets.json'
  cors:
    origin: 
      - '{{assets.host}}'
    methods:
      - 'GET'
    exposedHeaders: []
  cache:
    privacy: 'public'
    expiresIn: 604800000 #1 week
views:
  errors: false
  errorBlacklist: ^\/api
cache:
  partition: '{{name}}-cache'
admin:
  password: 'changeme'
