verbose: false
connection:
  port: "{{ENV.PORT || 8080}}"
  address: '0.0.0.0'
plugins:
  hapi-logr:
    type: 'json'
  hapi-method-loader:
    cwd: '{{CWD}}'
    verbose: '{{verbose}}'
  hapi-route-loader:
    cwd: '{{CWD}}'
    verbose: '{{verbose}}'
