verbose: false
server:
  debug: false
connection:
  port: "{{ENV.PORT || 8080}}"
  address: '0.0.0.0'
plugins:
  hapi-logr:
    _priority: -5
    reporters:
      flat:
        reporter: 'logr-flat'
        options:
          timestamp: false
  hapi-method-loader:
    _priority: 2
    cwd: '{{CWD}}'
    verbose: '{{verbose}}'
  hapi-route-loader:
    _priority: 3
    cwd: '{{CWD}}'
    verbose: '{{verbose}}'
