name: 'rapptor'
verbose: false
logType: '{{ envVars.logType }}'

server:
  debug: false
  routes:
    state:
      failAction: 'ignore'
  port: '{{ envVars.port }}'
  address: '0.0.0.0'
routePrefix: '{{ envVars.routePrefix }}'
plugins:
  hapi-favicon:
  hapi-health:
    token: '{{ envVars.healthToken }}'
    endpoint: '{{routePrefix}}/health'
    auth: false
  hapi-prom:
    _enabled: '{{ envVars.enableProm }}'
    metricsPath: '{{ envVars.promPath }}'
    defaultMetrics: '{{ envVars.promDefaults}}'
  hapi-logr:
    unhandledRejection: true
    uncaughtException: true
  hapi-require-https:
    _enabled: '{{ envVars.forceHttps }}'
  hapi-method-loader:
    cwd: '{{CWD}}'
    verbose: '{{verbose}}'
  hapi-route-loader:
    _dependencies:
      - 'hapi-method-loader'
    cwd: '{{CWD}}'
    prefix: '{{routePrefix}}'
    verbose: '{{verbose}}'
  hapi-log-response:
    requests: '{{ envVars.logRequests }}'
    includeEventTags: true
    ignoreUnauthorizedTry: true
    _dependencies:
      - 'hapi-trailing-slash'
    tags:
      - 'detailed-response'
  hapi-trailing-slash:
    method: 'remove'
