connection:
  port: 80
  address: '0.0.0.0'
mongo:
  host: 'localhost'
  port: '27017'
  db: 'rapptor-app'
structure:
  routes: 'routes'
logging:
  opsInterval: 15000
  reporters:
    console: false
    mongodb:
      - 'MONGOURL'
      -
         ttl: 604800
         events:
          request: '*'
          log: '*'
          error: '*'
plugins:
  good-mongodb-viewer:
    connectionUrl: 'MONGOURL'
    endpoint: '/_logs'
    searches:
      Responses: 'event:log AND tags:request-errors'
      Jobs: 'tags:agenda'
  hapi-log-response:
    enabled: false
    excludeStatus: [200, 206, 304, 302, 404]
    tags: ['request-errors']
  hapi-redirects:
    redirects: {}
