assets:
  compiled: '_dist'
  mapping: null
logging:
  reporters:
    console:
      enabled: true
      args:
        -
          log: '*'
          error: '*'
    mongodb:
      enabled: true
      args:
        - 'MONGOURL'
        -
           ttl: 604800
           events:
             response: '*'
             log: '*'
             error: '*'
plugins:
  hapi-output-cache:
    enabled: false
