plugins:
hapi-logr:
    _priority: -5
    reporters:
      consoleColor:
        reporter: 'logr-console-color'
        options:
          timestamp: false
      bell:
        reporter: 'logr-reporter-bell'
