plugins:
  hapi-logr:
    reporters:
      flat:
        options:
          enabled: false
      consoleColor:
        reporter: 'logr-console-color'
        options:
          timestamp: false
      bell:
        reporter: 'logr-reporter-bell'
