connection:
  port: 8080
logging:
  reporters:
    console:
      enabled: true
      args:
        -
          log: '*'
          response: '*'
    mongodb:
      enabled: true
      args:
        - 'MONGOURL'
        -
           ttl: 604800
           events:
             response: '*'
             log: '*'
             error: '*'
