plugins:
  hapi-logr:
    reporters:
      flat: null
      consoleColor:
        reporter: 'logr-console-color'
        options:
          timestamp: false
      bell:
        reporter: 'logr-reporter-bell'
