plugins:
  hapi-logr:
    reporters:
      flat:
        options:
          enabled: false
      consoleColor:
        options:
          enabled: true
      bell:
        reporter: 'logr-reporter-bell'
        options:
          enabled: true
