connection:
  port: "{{default ENV.PORT 8081}}"
testValue: 123
mongo:
  db: 'rapptor-example'
logging:
  reporters:
    hipchat:
      enabled: true
      args:
        -
          auth_token: ''
          room: ''
          roomToken: ''
          debug: true
          notify: false
          events:
            log:
              request-errors:
                color: 'yellow'
                notify: false
            error:
              '*':
                color: 'red'
                notify: true
assets:
  host: 'http://localhost:8081'
structure:
  partials: 'partials'
views:
  errors: 'errors'
plugins:
  hapi-redirects:
    redirects:
      '/test': '/'
  hapi-agenda:
    mongoUrl: '{{mongo.url}}'
    jobs: 'DIRNAME/jobs'
    processEvery: '5 seconds'
    #every:
      #'15 seconds': 'testJob'
