testValue: 123
mongo:
  db: 'rapptor-example'
logging:
  reporters:
    hipchat:
      - 
        auth_token: ''
        room: ''
        roomToken: ''
        debug: true
        notify: false
        events:
          log:
            request-errors:
              color: 'yellow'
              notify: false
          error:
            '*':
              color: 'red'
              notify: true
plugins:
  hapi-redirects:
    redirects:
      '/test': '/'
  hapi-agenda:
    mongoUrl: 'MONGOURL'
    jobs: 'DIRNAME/jobs'
    processEvery: '5 seconds'
    every:
      '15 seconds': 'testJob'
